// Package shells generates the init script for each shell: environment,
// PATH, core defaults, translated plugins and the prompt hook.
package shells

import (
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"opal/internal/ansi"
	"opal/internal/assets"
	"opal/internal/config"
	"opal/internal/platform"
	"opal/internal/plugin"
	"opal/internal/prompt"
	"opal/internal/theme"
)

// Supported lists the shells opal can initialize.
var Supported = []string{"zsh", "bash", "fish", "pwsh"}

// Normalize maps aliases like "powershell" to canonical shell names.
func Normalize(shell string) string {
	switch strings.ToLower(shell) {
	case "powershell", "pwsh", "ps", "ps1":
		return "pwsh"
	}
	return strings.ToLower(shell)
}

// Options feed the generator.
type Options struct {
	Cfg    *config.Config
	CfgErr error
	Theme  *theme.Theme
	Bin    string // absolute path to this binary
	Info   platform.Info
	Has    func(string) bool

	// The banner shows once per terminal: TermID names this one, and Greeted
	// is the terminal an enclosing shell already greeted ($OPAL_GREETED).
	TermID  string
	Greeted string
}

// greets reports whether this shell opens a terminal nobody has greeted yet.
func (o Options) greets() bool { return o.Cfg.Greeting && o.TermID != o.Greeted }

// Generate returns the init script for shell.
func Generate(shell string, o Options) (string, error) {
	shell = Normalize(shell)
	t := config.Target{Shell: shell, OS: o.Info.OS, WSL: o.Info.WSL}
	res := plugin.Resolve(o.Cfg, t, o.Has)
	g := &gen{shell: shell, o: o, res: res}
	switch shell {
	case "zsh", "bash":
		return g.posix(), nil
	case "fish":
		return g.fish(), nil
	case "pwsh":
		return g.pwsh(), nil
	}
	return "", fmt.Errorf("unsupported shell %q (supported: %s)", shell, strings.Join(Supported, ", "))
}

type gen struct {
	shell string
	o     Options
	res   plugin.Result
	b     strings.Builder
}

func (g *gen) line(format string, args ...any) {
	fmt.Fprintf(&g.b, format, args...)
	g.b.WriteByte('\n')
}

// section starts a titled block in the generated script.
func (g *gen) section(title string) {
	g.line("")
	g.line("# %s", title)
}

func (g *gen) header() {
	g.line("# opal init - %s - generated by `opal init %s`", g.shell, g.shell)
	file := g.o.Cfg.File
	if g.shell == "pwsh" && !isASCII(file) {
		file = "~/.config/opal/config.toml"
	}
	g.line("# Edit %s instead of this output.", file)
}

// pathDirs returns config PATH entries that exist and aren't already on PATH,
// in shell spelling.
func (g *gen) pathDirs() []string {
	current := map[string]bool{}
	for _, p := range filepath.SplitList(os.Getenv("PATH")) {
		current[normPath(p)] = true
	}
	var out []string
	for _, p := range g.o.Cfg.Path {
		p = expand(p)
		if fi, err := os.Stat(p); err != nil || !fi.IsDir() {
			continue
		}
		if current[normPath(p)] {
			continue
		}
		current[normPath(p)] = true
		out = append(out, platform.ShellPath(p, g.shell))
	}
	return out
}

func normPath(p string) string {
	p = filepath.Clean(p)
	if runtime.GOOS == "windows" {
		return strings.ToLower(p)
	}
	return p
}

// expand resolves ~ and $VAR in config values.
func expand(s string) string {
	home := platform.Home()
	if s == "~" {
		return home
	}
	if strings.HasPrefix(s, "~/") || strings.HasPrefix(s, `~\`) {
		s = filepath.Join(home, s[2:])
	}
	return os.Expand(s, func(k string) string {
		if v, ok := os.LookupEnv(k); ok {
			return v
		}
		if k == "HOME" {
			return home
		}
		return "$" + k
	})
}

func (g *gen) palette() (*theme.Palette, int) {
	return g.o.Theme.Resolve(g.o.Cfg.Background, g.shell), platform.ColorDepth(g.o.Cfg.Color)
}

// continuation renders the PS2-style prompt for this shell.
func (g *gen) continuation() string {
	p, depth := g.palette()
	glyph := "·"
	if platform.IconSet(g.o.Cfg.Icons) == "ascii" {
		glyph = "."
	}
	return prompt.Encode([][]prompt.Span{{{Text: glyph, FG: p.C("muted")}, {Text: " "}}}, g.shell, depth)
}

func (g *gen) byPlugin(defs []plugin.Def) ([]string, map[string][]plugin.Def) {
	groups := map[string][]plugin.Def{}
	var order []string
	for _, d := range defs {
		if _, ok := groups[d.Plugin]; !ok {
			order = append(order, d.Plugin)
		}
		groups[d.Plugin] = append(groups[d.Plugin], d)
	}
	return order, groups
}

// onPath reports whether `opal` on PATH (as the calling shell sees it) is
// this binary, so the init can skip defining a fallback.
func (g *gen) onPath() bool {
	found, ok := platform.LookPath("opal")
	if !ok {
		return false
	}
	a, errA := os.Stat(found)
	b, errB := os.Stat(g.o.Bin)
	return errA == nil && errB == nil && os.SameFile(a, b)
}

// completion wires tab completion to `opal complete`, in each shell's own way.
func (g *gen) completion() {
	names := []string{"opal"}
	var gitAliases []string
	for _, d := range g.res.Defs {
		if d.Name == "j" && d.Func {
			names = append(names, "j")
			continue
		}
		if d.Func {
			continue
		}
		f := strings.Fields(d.Body)
		if len(f) == 0 {
			continue
		}
		switch {
		case f[0] == "opal" && g.shell != "zsh" && g.shell != "fish":
			names = append(names, d.Name) // zsh/fish expand aliases before completing
		case f[0] == "git" && g.shell == "pwsh":
			names = append(names, d.Name)
		case f[0] == "git" && g.shell == "bash" && shName.MatchString(d.Name):
			sub := "__main"
			if len(f) > 1 && !strings.HasPrefix(f[1], "-") {
				sub = f[1]
			}
			gitAliases = append(gitAliases, d.Name+"="+sub)
		}
	}
	g.section("completion")
	var src string
	switch g.shell {
	case "pwsh":
		names = append(names, "git")
		q := make([]string, 0, len(names))
		for _, n := range names {
			if psName.MatchString(n) {
				q = append(q, psQuote(n))
			}
		}
		src = strings.ReplaceAll(assets.ShellFile("complete.ps1"), "@@NAMES@@", strings.Join(q, ","))
	case "bash":
		src = strings.ReplaceAll(assets.ShellFile("complete.bash"), "@@NAMES@@", strings.Join(names, " "))
		src = strings.ReplaceAll(src, "@@GITALIASES@@", strings.Join(gitAliases, " "))
	default:
		src = strings.ReplaceAll(assets.ShellFile("complete."+g.shell), "@@NAMES@@", strings.Join(names, " "))
	}
	g.b.WriteString(src)
}

// ---------------------------------------------------------------- zsh / bash

func (g *gen) posix() string {
	g.header()
	version := "$ZSH_VERSION"
	if g.shell == "bash" {
		version = "$BASH_VERSION"
	}
	g.line("export OPAL_SHELL=%s", g.shell)
	g.line("export OPAL_SHELL_VERSION=\"%s\"", version)
	g.line("export OPAL_BIN=%s", shQuote(platform.ShellPath(g.o.Bin, g.shell)))
	g.line(`command -v opal >/dev/null 2>&1 || opal() { "$OPAL_BIN" "$@"; }`)
	if g.o.CfgErr != nil {
		g.line("printf '%%s\\n' %s >&2", shQuote("opal: "+g.o.CfgErr.Error()+" (using defaults)"))
	}

	g.section("environment")
	for _, e := range g.res.Env {
		if envName.MatchString(e.Name) {
			g.line("export %s=%s", e.Name, shQuote(expand(e.Body)))
		}
	}
	if dirs := g.pathDirs(); len(dirs) > 0 {
		g.line("export PATH=%s\"${PATH:+:$PATH}\"", shQuote(strings.Join(dirs, ":")))
	}

	if g.o.Cfg.Core.Defaults {
		g.section("core defaults")
		g.b.WriteString(assets.ShellFile("core." + g.shell))
	}

	order, groups := g.byPlugin(g.res.Defs)
	for _, name := range order {
		g.section("plugin: " + name)
		for _, d := range groups[name] {
			if !shName.MatchString(d.Name) {
				continue
			}
			if d.Func {
				g.line("unalias %s 2>/dev/null", shQuote(d.Name))
				if d.Desc != "" {
					g.line("# %s", d.Desc)
				}
				g.line("function %s {", d.Name)
				g.line("  %s", strings.TrimSpace(d.Body))
				g.line("}")
			} else {
				g.line("alias -- %s=%s", d.Name, shQuote(d.Body))
			}
		}
	}
	for _, n := range g.res.Native {
		g.section("native: " + n.Plugin)
		g.line("%s", strings.TrimRight(n.Body, "\n"))
	}

	g.completion()
	g.externalCompletions()
	g.section("prompt")
	tps, markC := g.promptExtras()
	hist := ""
	if g.o.Cfg.History.Shared {
		hist = "1"
	}
	if g.shell == "zsh" {
		g.line("typeset -g _opal_hist=%s _opal_tps=%s _opal_mark_c=%s", shQuote(hist), ansiCQuote(tps), ansiCQuote(markC))
	} else {
		// PS0 is decoded like PS1, so its mark ends in BEL rather than ESC \.
		g.line("_opal_hist=%s _opal_mark_c=%s", shQuote(hist), ansiCQuote(strings.ReplaceAll(markC, "\x1b\\", "\a")))
	}
	g.b.WriteString(assets.ShellFile("prompt." + g.shell))
	if g.shell == "zsh" {
		g.line("PROMPT2=%s", ansiCQuote(g.continuation()))
		g.zshHighlight()
		if g.o.Cfg.Suggest {
			g.section("suggestions")
			if c, ok := g.suggestColor(); ok {
				g.line("typeset -g _opal_sugg_style=%s", shQuote("fg="+strings.ToLower(c.Hex())))
			}
			g.b.WriteString(assets.ShellFile("suggest.zsh"))
		}
	} else {
		g.line("PS2=%s", ansiCQuote(g.continuation()))
	}
	if g.o.Cfg.History.CtrlR {
		g.section("history")
		g.b.WriteString(assets.ShellFile("history." + g.shell))
	}
	if g.shell == "bash" && g.o.Cfg.Suggest {
		g.section("suggestions")
		g.b.WriteString(assets.ShellFile("suggest.bash"))
	}

	if g.o.greets() {
		g.section("greeting")
		g.line(`if [[ $- == *i* ]] && [ -t 1 ]; then`)
		g.line(`  "$OPAL_BIN" greet --hook --width "${COLUMNS:-0}"`)
		g.line(`  export OPAL_GREETED=%s`, shQuote(g.o.TermID))
		g.line(`fi`)
	}
	if g.shell == "bash" && g.o.Cfg.Suggest {
		g.line("if [[ -n ${_opal_blesh-} ]]; then ble-attach; fi # last, once everything is set up")
	}
	return g.b.String()
}

// zshHighlight themes zsh-syntax-highlighting and zsh-autosuggestions if the
// user loads them, without overriding styles they've set themselves.
func (g *gen) zshHighlight() {
	p, depth := g.palette()
	if depth < 256 {
		return
	}
	syn := g.o.Theme.SyntaxColors(p)
	styles := map[string]string{
		"command": "command", "builtin": "command", "alias": "command", "function": "command",
		"reserved-word": "keyword", "precommand": "keyword",
		"single-hyphen-option": "parameter", "double-hyphen-option": "parameter",
		"single-quoted-argument": "string", "double-quoted-argument": "string", "dollar-quoted-argument": "string",
		"commandseparator": "operator", "redirection": "operator",
		"comment": "comment", "unknown-token": "error",
	}
	keys := make([]string, 0, len(styles))
	for k := range styles {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	g.line("typeset -gA ZSH_HIGHLIGHT_STYLES")
	for _, k := range keys {
		if c, ok := syn[styles[k]]; ok && c.Set {
			g.line(": ${ZSH_HIGHLIGHT_STYLES[%s]:=fg=%s}", k, strings.ToLower(c.Hex()))
		}
	}
	if c, ok := syn["suggestion"]; ok && c.Set {
		g.line(": ${ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE:=fg=%s}", strings.ToLower(c.Hex()))
	}
}

// ---------------------------------------------------------------- fish

func (g *gen) fish() string {
	g.header()
	g.line("set -gx OPAL_SHELL fish")
	g.line("set -gx OPAL_SHELL_VERSION $version")
	g.line("set -gx OPAL_BIN %s", fishQuote(platform.ShellPath(g.o.Bin, "fish")))
	g.line("if not type -q opal")
	g.line("    function opal; command $OPAL_BIN $argv; end")
	g.line("end")
	if g.o.CfgErr != nil {
		g.line("echo %s >&2", fishQuote("opal: "+g.o.CfgErr.Error()+" (using defaults)"))
	}

	g.section("environment")
	for _, e := range g.res.Env {
		if envName.MatchString(e.Name) {
			g.line("set -gx %s %s", e.Name, fishQuote(expand(e.Body)))
		}
	}
	if dirs := g.pathDirs(); len(dirs) > 0 {
		q := make([]string, len(dirs))
		for i, d := range dirs {
			q[i] = fishQuote(d)
		}
		g.line("set -gx PATH %s $PATH", strings.Join(q, " "))
	}

	if g.o.Cfg.Core.Defaults {
		g.section("core defaults")
		g.b.WriteString(assets.ShellFile("core.fish"))
		if !g.o.Cfg.Shell.Fish.Greeting {
			g.line("set -g fish_greeting ''")
		}
	}

	abbr := g.o.Cfg.Shell.Fish.Abbreviations
	order, groups := g.byPlugin(g.res.Defs)
	for _, name := range order {
		g.section("plugin: " + name)
		for _, d := range groups[name] {
			if !fishName.MatchString(d.Name) {
				continue
			}
			switch {
			case d.Func:
				desc := ""
				if d.Desc != "" {
					desc = " --description " + fishQuote(d.Desc)
				}
				g.line("functions -q %s; and functions -e %s", d.Name, d.Name)
				g.line("function %s%s", d.Name, desc)
				g.line("    %s", strings.TrimSpace(d.Body))
				g.line("end")
			case abbr:
				g.line("abbr -a -g -- %s %s", d.Name, fishQuote(d.Body))
			default:
				body := d.Body
				if firstWord(body) == d.Name {
					body = "command " + body
				}
				g.line("function %s --wraps %s --description %s", d.Name, fishQuote(d.Body), fishQuote("alias "+d.Name+"="+d.Body))
				g.line("    %s $argv", body)
				g.line("end")
			}
		}
	}
	for _, n := range g.res.Native {
		g.section("native: " + n.Plugin)
		g.line("%s", strings.TrimRight(n.Body, "\n"))
	}

	g.completion()
	g.externalCompletions()
	g.section("prompt")
	tps, markC := g.promptExtras()
	hist := ""
	if g.o.Cfg.History.Shared {
		hist = "1"
	}
	g.line("set -g _opal_hist %s", fishQuote(hist))
	g.line("set -g _opal_tps %s", fishEscape(tps))
	g.line("set -g _opal_mark_c %s", fishEscape(markC))
	g.b.WriteString(assets.ShellFile("prompt.fish"))
	g.fishColors()
	if g.o.Cfg.History.CtrlR {
		g.section("history")
		g.b.WriteString(assets.ShellFile("history.fish"))
	}

	if g.o.greets() {
		g.section("greeting")
		g.line("if status is-interactive; and test -t 1")
		g.line("    command $OPAL_BIN greet --hook --width $COLUMNS")
		g.line("    set -gx OPAL_GREETED %s", fishQuote(g.o.TermID))
		g.line("end")
	}
	return g.b.String()
}

func (g *gen) fishColors() {
	p, depth := g.palette()
	if depth == 0 {
		return
	}
	syn := g.o.Theme.SyntaxColors(p)
	vars := [][2]string{
		{"fish_color_command", "command"}, {"fish_color_keyword", "keyword"},
		{"fish_color_param", "parameter"}, {"fish_color_option", "parameter"},
		{"fish_color_quote", "string"}, {"fish_color_escape", "number"},
		{"fish_color_operator", "operator"}, {"fish_color_end", "operator"},
		{"fish_color_redirection", "variable"}, {"fish_color_comment", "comment"},
		{"fish_color_error", "error"}, {"fish_color_autosuggestion", "suggestion"},
		{"fish_pager_color_prefix", "command"}, {"fish_pager_color_description", "comment"},
	}
	for _, v := range vars {
		if c, ok := syn[v[1]]; ok && c.Set {
			g.line("set -g %s %s", v[0], strings.TrimPrefix(c.Hex(), "#"))
		}
	}
}

// ---------------------------------------------------------------- PowerShell

func (g *gen) pwsh() string {
	g.header()
	g.line(`$env:OPAL_SHELL = 'pwsh'`)
	g.line(`$env:OPAL_SHELL_VERSION = $PSVersionTable.PSVersion.ToString()`)
	g.line(`$env:OPAL_BIN = %s`, psQuote(g.o.Bin))
	// Startup time matters on Windows PowerShell: ::new() skips New-Object's
	// cmdlet overhead, and PATH is checked here rather than by a slow Get-Command.
	g.line(`$global:__opal_utf8 = [System.Text.UTF8Encoding]::new($false)`)
	if !g.onPath() {
		g.line(`function global:opal { & $env:OPAL_BIN @args }`)
	}
	g.line(`if ($PSVersionTable.PSEdition -eq 'Desktop' -or $IsWindows) {`)
	g.line(`    try {`)
	g.line(`        $__opal_id = [Security.Principal.WindowsIdentity]::GetCurrent()`)
	g.line(`        if ((New-Object Security.Principal.WindowsPrincipal $__opal_id).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) { $env:OPAL_ADMIN = '1' }`)
	g.line(`    } catch { }`)
	g.line(`}`)
	if g.o.Cfg.Shell.Pwsh.UTF8 {
		g.line(`try { [Console]::OutputEncoding = $global:__opal_utf8 } catch { } # throws in consoleless hosts`)
		g.line(`$global:OutputEncoding = $global:__opal_utf8`)
	}
	if g.o.CfgErr != nil {
		g.line("Write-Warning %s", psQuote("opal: "+g.o.CfgErr.Error()+" (using defaults)"))
	}

	g.section("environment")
	for _, e := range g.res.Env {
		if envName.MatchString(e.Name) {
			g.line("$env:%s = %s", e.Name, psQuote(expand(e.Body)))
		}
	}
	if dirs := g.pathDirs(); len(dirs) > 0 {
		sep := string(filepath.ListSeparator)
		g.line("$env:PATH = %s + $env:PATH", psQuote(strings.Join(dirs, sep)+sep))
	}

	if g.o.Cfg.Core.Defaults {
		g.section("core defaults")
		g.b.WriteString(assets.ShellFile("core.ps1"))
	}

	g.section("plugins")
	var names []string
	for _, d := range g.res.Defs {
		if psName.MatchString(d.Name) {
			names = append(names, psQuote(d.Name))
		}
	}
	// PowerShell resolves aliases before functions, so a built-in alias (gc,
	// gl, gp, gcm...) would shadow ours. Keep built-ins unless told otherwise.
	// This runs at global scope so AllScope aliases really go away.
	// (A lookup table, not Test-Path Alias:x: that treats ".." as a path.)
	g.line(`$global:OpalSkipped = @()`)
	g.line(`$__opal_have = @{}; foreach ($__opal_a in Get-Alias) { $__opal_have[$__opal_a.Name] = 1 }`)
	g.line(`foreach ($__opal_n in @(%s)) {`, strings.Join(names, ","))
	g.line(`    if (-not $__opal_have.ContainsKey($__opal_n)) { continue }`)
	if g.o.Cfg.Shell.Pwsh.ClobberBuiltinAliases {
		g.line(`    Remove-Item -LiteralPath "Alias:$__opal_n" -Force -ErrorAction SilentlyContinue`)
		g.line(`    if (Get-Alias -Name $__opal_n -ErrorAction SilentlyContinue) { $global:OpalSkipped += $__opal_n }`)
	} else {
		g.line(`    $global:OpalSkipped += $__opal_n`)
	}
	g.line(`}`)
	order, groups := g.byPlugin(g.res.Defs)
	for _, name := range order {
		g.line("# %s", name)
		for _, d := range groups[name] {
			if !psName.MatchString(d.Name) {
				continue
			}
			body := strings.TrimSpace(d.Body)
			if !d.Func {
				cmd := body
				if strings.EqualFold(firstWord(cmd), d.Name) {
					// Calling itself would recurse; reach for the real command.
					cmd = fmt.Sprintf("& (Get-Command -Name %s -CommandType Application,Cmdlet | Select-Object -First 1)%s",
						psQuote(d.Name), strings.TrimPrefix(cmd, firstWord(cmd)))
				}
				body = fmt.Sprintf("if ($MyInvocation.ExpectingInput) { $input | %s @args } else { %s @args }", cmd, cmd)
			}
			guard := fmt.Sprintf("if ($global:OpalSkipped -notcontains %s)", psQuote(d.Name))
			if !isASCII(body) {
				g.line("%s { Set-Item -Path %s -Value ([scriptblock]::Create(%s)) }",
					guard, psQuote("Function:global:"+d.Name), psQuote(body))
				continue
			}
			g.line("%s { function global:%s {", guard, d.Name)
			g.line("    %s", body)
			g.line("} }")
		}
	}
	for _, n := range g.res.Native {
		g.section("native: " + n.Plugin)
		body := strings.TrimRight(n.Body, "\n")
		if isASCII(body) {
			g.line("%s", body)
		} else {
			g.line(". ([scriptblock]::Create(%s))", psQuote(body))
		}
	}

	g.completion()
	g.externalCompletions()
	g.section("prompt")
	tps, markC := g.promptExtras()
	g.line(`$global:__opal_e = [char]27`)
	g.line(`$global:__opal_record = $%t`, g.o.Cfg.History.Shared)
	g.line(`$global:__opal_ctrl_r = $%t`, g.o.Cfg.History.CtrlR)
	g.line(`$global:__opal_tps = %s`, psSeqGlobal(tps))
	g.line(`$global:__opal_mark_c = %s`, psSeqGlobal(markC))
	g.b.WriteString(assets.ShellFile("prompt.ps1"))
	g.pwshReadLine()

	if g.o.greets() {
		// Like the prompt, capture opal's UTF-8 output and hand it to the host.
		g.section("greeting")
		g.line(`if ($Host.Name -eq 'ConsoleHost' -and -not [Console]::IsOutputRedirected -and -not ([Environment]::GetCommandLineArgs() -match '^[-/]noni')) {`)
		g.line(`    $__opal_w = 0`)
		g.line(`    try { $__opal_w = $Host.UI.RawUI.WindowSize.Width } catch { }`)
		g.line(`    $__opal_enc = [Console]::OutputEncoding`)
		g.line(`    if ($__opal_enc.CodePage -ne 65001) { [Console]::OutputEncoding = $global:__opal_utf8 }`)
		g.line(`    try { $__opal_g = & $env:OPAL_BIN greet --hook --width $__opal_w } finally { [Console]::OutputEncoding = $__opal_enc }`)
		g.line(`    if ($__opal_g) { Write-Host ($__opal_g -join "` + "`" + `n") }`)
		g.line(`    $env:OPAL_GREETED = %s`, psQuote(g.o.TermID))
		g.line(`    Remove-Variable __opal_w, __opal_enc, __opal_g -ErrorAction SilentlyContinue`)
		g.line(`}`)
	}
	return g.b.String()
}

func (g *gen) pwshReadLine() {
	p, depth := g.palette()
	g.line(`if (Get-Module -Name PSReadLine) {`)
	extra := g.o.Theme.Lines - 1
	if g.o.Cfg.Prompt.BlankLine {
		extra++
	}
	if extra > 0 {
		g.line(`    Set-PSReadLineOption -ExtraPromptLineCount %d`, extra)
	}
	g.line(`    $__opal_e = [char]27`)
	g.line(`    Set-PSReadLineOption -ContinuationPrompt %s`, psSeq(g.continuation()))
	if depth > 0 {
		syn := g.o.Theme.SyntaxColors(p)
		names := [][2]string{
			{"Command", "command"}, {"Keyword", "keyword"}, {"Parameter", "parameter"},
			{"String", "string"}, {"Number", "number"}, {"Operator", "operator"},
			{"Variable", "variable"}, {"Member", "variable"}, {"Type", "keyword"},
			{"Comment", "comment"}, {"Error", "error"},
		}
		var pairs []string
		for _, n := range names {
			if c, ok := syn[n[1]]; ok && c.Set {
				pairs = append(pairs, fmt.Sprintf("%s = %s", n[0], psColor(c, depth)))
			}
		}
		if len(pairs) > 0 {
			g.line(`    Set-PSReadLineOption -Colors @{ %s }`, strings.Join(pairs, "; "))
		}
		if c, ok := syn["suggestion"]; ok && c.Set {
			g.line(`    if ((Get-Module PSReadLine).Version -ge [version]'2.1.0') { Set-PSReadLineOption -Colors @{ InlinePrediction = %s } }`, psColor(c, depth))
		}
	}
	g.line(`}`)
}

// psColor renders an SGR color as a PowerShell string built from [char]27,
// which works on Windows PowerShell 5.1 (no "`e" escape there).
func psColor(c ansi.Color, depth int) string {
	return `"${__opal_e}[` + c.FG(depth) + `m"`
}

// promptExtras returns the transient prompt (empty when turned off) and the
// "command output starts" mark (empty when marks are off), for this shell.
func (g *gen) promptExtras() (transient, markC string) {
	depth := platform.ColorDepth(g.o.Cfg.Color)
	marks := prompt.MarksEnabled(g.o.Cfg.Prompt.SemanticMarks, depth)
	if marks {
		markC = prompt.MarkOutputStart
	}
	if g.o.Cfg.Prompt.Transient && g.shell != "bash" { // readline can't redraw a finished prompt
		c := prompt.NewContext(g.o.Cfg, g.o.Theme, g.shell)
		transient = prompt.Transient(c, depth, marks)
	}
	return transient, markC
}

// suggestColor is the theme's color for grey as-you-type suggestions.
func (g *gen) suggestColor() (ansi.Color, bool) {
	p, depth := g.palette()
	if depth < 256 {
		return ansi.Color{}, false
	}
	c, ok := g.o.Theme.SyntaxColors(p)["suggestion"]
	return c, ok && c.Set
}

// fishEscape renders s for fish with ESC spelled \e (outside quotes).
func fishEscape(s string) string {
	if s == "" {
		return "''"
	}
	parts := strings.Split(s, "\x1b")
	var b strings.Builder
	for i, p := range parts {
		if i > 0 {
			b.WriteString(`\e`)
		}
		if p != "" {
			b.WriteString(fishQuote(p))
		}
	}
	return b.String()
}

// psSeqGlobal is psSeq for top-level assignments, where $__opal_e is global.
func psSeqGlobal(s string) string {
	if s == "" {
		return "''"
	}
	return strings.ReplaceAll(psSeq(s), "$__opal_e", "$global:__opal_e")
}

// psSeq turns a string containing ESC into an ASCII PowerShell expression.
func psSeq(s string) string {
	parts := strings.Split(s, "\x1b")
	q := make([]string, len(parts))
	for i, p := range parts {
		q[i] = psQuote(p)
	}
	return "(" + strings.Join(q, " + $__opal_e + ") + ")"
}

// Wrap makes the PowerShell init safe to pass through Invoke-Expression even
// when it contains non-ASCII (e.g. a user's alias): PowerShell may decode our
// output with a legacy code page, so ship it base64-encoded in that case.
func Wrap(shell, script string) string {
	if shell != "pwsh" || isASCII(script) {
		return script
	}
	enc := base64.StdEncoding.EncodeToString([]byte(script))
	return "# opal init (non-ASCII content, base64 so no code page can mangle it)\n" +
		". ([scriptblock]::Create([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('" + enc + "'))))\n"
}
